# Generated by Django 2.2.7 on 2019-11-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchnote',
            name='written_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
