# Generated by Django 2.2.7 on 2019-11-10 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_note', '0002_auto_20191110_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchnote',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_notes', to='research_note.Issue'),
        ),
    ]
