# Generated by Django 2.2.7 on 2019-11-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_note', '0003_auto_20191110_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchnote',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
