# Generated by Django 2.2.7 on 2019-11-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research_note', '0004_auto_20191110_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchnote',
            name='is_written',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
